file: /tutorial/replace-config-server
description: |
  Replace a config server in a config server replica set.
---
file: /tutorial/upgrade-config-servers-to-replica-set
description: |
  Perform a rolling upgrade a mirrored config server deployment
  to a replica set. MongoDB 3.2+ only.
---
file: /tutorial/upgrade-config-servers-to-replica-set-downtime
description: |
  Upgrade a mirrored config server deployment to a replica set. 
  MongoDB 3.2+ only.
...
