# - 'before-<branch>': bit of a misnomer -- it is up to and including
#                      the branch specified
#
from: /core/views
to: /core/databases-and-collections
type: 'redirect'
code: 303
outputs:
  - 'before-v3.2'
---
from: /reference/method/db.createView
to: /reference/method/db.createCollection
type: 'redirect'
code: 303
outputs:
  - 'before-v3.2'
---
from: '/core/zone-sharding'
to: '/core/tag-aware-sharding'
type: 'redirect'
code: 301
outputs:
  - 'before-v3.4'
---
from: '/tutorial/manage-shard-zone'
to: '/tutorial/administer-shard-tags'
type: 'redirect'
code: 301
outputs:
  - 'before-v3.4'
---
from: '/core/tag-aware-sharding'
to: '/core/zone-sharding'
type: 'redirect'
code: 301
outputs:
  - 'after-v3.2'
---
from: '/tutorial/administer-shard-tags'
to: '/tutorial/manage-shard-zone'
type: 'redirect'
code: 301
outouts:
  - 'after-v3.2'
...
