# - 'before-<branch>': bit of a misnomer -- it is up to and including
#                      the branch specified
#
from: /core/views
to: /core/databases-and-collections
type: 'redirect'
code: 303
outputs:
  - 'before-v3.2'
---
from: /reference/method/db.createView
to: /reference/method/db.createCollection
type: 'redirect'
code: 303
outputs:
  - 'before-v3.2'
...
