# Each redirect YAML document has the following schema:
#
#    from: "the path to the redirected URL"
#    url-base: "the path to the new location for the resource"
#    type: "currently this script only supports 'redirect', and
#          ignores all documents with another type."
#    code: "the HTTP redirect code. Raises exception if not 301, 302, 303."
#    outputs: "a list of branches/paths beneath http://docs.mongodb.com/ to
#             place this redirect. 'all', 'before-<branch>' and
#             'after-<branch>' have special meaning.
#
# 'outputs' possibility:
#
# - 'all': generates redirects for all published branches, but *not* 'manual'.
#
# - '<branch>': generates redirects for a specific branch.
#
# - 'before-<branch>': generates redirects for all branches that
#   reflect releases previous to the specified branch. (Inclusive.)
#   bit of a misnomer -- it is up to and including
#
# - 'after-<branch>': generates redirects for all branches that
#   reflect releases after the specified branch. (Non-inclusive.)
#
# All paths are relative to the ``source/`` directory.
#
########################################################################

from: /reference/command/captrunc
to: /reference/command/
type: 'redirect'
code: 303
outputs:
  - 'all'
  - 'manual'
---
from: /reference/command/configureFailPoint
to: /reference/command/
type: 'redirect'
code: 303
outputs:
  - 'all'
  - 'manual'
---
from: /reference/command/emptycapped
to: /reference/command/
type: 'redirect'
code: 303
outputs:
  - 'all'
  - 'manual'
---
from: /reference/command/forceerror
to: /reference/command/
type: 'redirect'
code: 303
outputs:
  - 'all'
  - 'manual'
---
from: /reference/command/godinsert
to: /reference/command/
type: 'redirect'
code: 303
outputs:
  - 'all'
  - 'manual'
---
from: /reference/command/hashBSONElement
to: /reference/command/
type: 'redirect'
code: 303
outputs:
  - 'all'
  - 'manual'
---
from: /reference/command/journalLatencyTest
to: /reference/command/
type: 'redirect'
code: 303
outputs:
  - 'all'
  - 'manual'
---
from: /reference/command/replSetTest
to: /reference/command/
type: 'redirect'
code: 303
outputs:
  - 'all'
  - 'manual'
---
from: /reference/command/skewClockCommand
to: /reference/command/
type: 'redirect'
code: 303
outputs:
  - 'all'
  - 'manual'
---
from: /reference/command/sleep
to: /reference/command/
type: 'redirect'
code: 303
outputs:
  - 'all'
  - 'manual'
---
from: /reference/command/testDistLockWithSkew
to: /reference/command/
type: 'redirect'
code: 303
outputs:
  - 'all'
  - 'manual'
---
from: /reference/command/testDistLockWithSyncCluster
to: /reference/command/
type: 'redirect'
code: 303
outputs:
  - 'all'
  - 'manual'
---
from: /command/nav-testing
to: /reference/command/
type: 'redirect'
code: 303
outputs:
  - 'all'
  - 'manual'
...
